version: "3"
services:
  # mongodb:
  #   image: "mongo:3.6.13-xenial"
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  # rabbitmq:
  #   image: "rabbitmq:3.8.3-management-alpine"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb
  chronograf:
    image: chronograf:latest
    ports:
      - 8888:8888
    volumes:
      - chronograf-data:/var/lib/chronograf
volumes:
  # mongo-data:
  #   driver: local
  influx-data:
    driver: local
  chronograf-data:
    driver: local
